// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomepageDocumentDataSlicesSlice =
  | DuringTherapySlice
  | PersonalizedSlice
  | GetBackSlice
  | HeroSlice;

/**
 * Content for homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Item in *Settings → Navigation*
 */
export interface SettingsDocumentDataNavigationItem {
  /**
   * Link field in *Settings → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Label field in *Settings → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * Meta description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * OG image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  og_image: prismic.ImageField<never>;

  /**
   * Navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation: prismic.GroupField<Simplify<SettingsDocumentDataNavigationItem>>;

  /**
   * Nav Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.nav_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  nav_logo: prismic.ImageField<never>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes = HomepageDocument | SettingsDocument;

/**
 * Primary content in *DuringTherapy → Default → Primary*
 */
export interface DuringTherapySliceDefaultPrimary {
  /**
   * title_color field in *DuringTherapy → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: during_therapy.default.primary.title_color
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title_color: prismic.RichTextField;

  /**
   * title field in *DuringTherapy → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: during_therapy.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *DuringTherapy → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: during_therapy.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for DuringTherapy Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DuringTherapySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DuringTherapySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *DuringTherapy*
 */
type DuringTherapySliceVariation = DuringTherapySliceDefault;

/**
 * DuringTherapy Shared Slice
 *
 * - **API ID**: `during_therapy`
 * - **Description**: DuringTherapy
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DuringTherapySlice = prismic.SharedSlice<
  "during_therapy",
  DuringTherapySliceVariation
>;

/**
 * Item in *GetBack → Default → Primary → get Back Text*
 */
export interface GetBackSliceDefaultPrimaryGetBackTextItem {
  /**
   * Text field in *GetBack → Default → Primary → get Back Text*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: get_back.default.primary.get_back_text[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Item in *GetBack → ImageLeftBgWhite → Primary → get Back Text*
 */
export interface GetBackSliceLeftToRightPrimaryGetBackTextItem {
  /**
   * Text field in *GetBack → ImageLeftBgWhite → Primary → get Back Text*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: get_back.leftToRight.primary.get_back_text[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Item in *GetBack → bg_gray_Image_right → Primary → get Back Text*
 */
export interface GetBackSliceBgGrayPrimaryGetBackTextItem {
  /**
   * Text field in *GetBack → bg_gray_Image_right → Primary → get Back Text*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: get_back.bgGray.primary.get_back_text[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Item in *GetBack → bg_gray_image_left → Primary → get Back Text*
 */
export interface GetBackSliceBgGrayImageLeftPrimaryGetBackTextItem {
  /**
   * Text field in *GetBack → bg_gray_image_left → Primary → get Back Text*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: get_back.bgGrayImageLeft.primary.get_back_text[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Primary content in *GetBack → Default → Primary*
 */
export interface GetBackSliceDefaultPrimary {
  /**
   * Main Image field in *GetBack → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: get_back.default.primary.main_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  main_image: prismic.ImageField<never>;

  /**
   * colortext field in *GetBack → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: get_back.default.primary.colortext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  colortext: prismic.RichTextField;

  /**
   * Title field in *GetBack → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: get_back.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * get Back Text field in *GetBack → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: get_back.default.primary.get_back_text[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  get_back_text: prismic.GroupField<
    Simplify<GetBackSliceDefaultPrimaryGetBackTextItem>
  >;

  /**
   * underLine field in *GetBack → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: get_back.default.primary.underline
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  underline: prismic.ImageField<never>;
}

/**
 * Default variation for GetBack Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GetBackSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GetBackSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *GetBack → ImageLeftBgWhite → Primary*
 */
export interface GetBackSliceLeftToRightPrimary {
  /**
   * Main Image field in *GetBack → ImageLeftBgWhite → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: get_back.leftToRight.primary.main_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  main_image: prismic.ImageField<never>;

  /**
   * Title field in *GetBack → ImageLeftBgWhite → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: get_back.leftToRight.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * colorText field in *GetBack → ImageLeftBgWhite → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: get_back.leftToRight.primary.colortext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  colortext: prismic.RichTextField;

  /**
   * get Back Text field in *GetBack → ImageLeftBgWhite → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: get_back.leftToRight.primary.get_back_text[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  get_back_text: prismic.GroupField<
    Simplify<GetBackSliceLeftToRightPrimaryGetBackTextItem>
  >;

  /**
   * color field in *GetBack → ImageLeftBgWhite → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: get_back.leftToRight.primary.color
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  color: prismic.RichTextField;

  /**
   * underLine field in *GetBack → ImageLeftBgWhite → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: get_back.leftToRight.primary.underline
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  underline: prismic.ImageField<never>;
}

/**
 * ImageLeftBgWhite variation for GetBack Slice
 *
 * - **API ID**: `leftToRight`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GetBackSliceLeftToRight = prismic.SharedSliceVariation<
  "leftToRight",
  Simplify<GetBackSliceLeftToRightPrimary>,
  never
>;

/**
 * Primary content in *GetBack → bg_gray_Image_right → Primary*
 */
export interface GetBackSliceBgGrayPrimary {
  /**
   * Main Image field in *GetBack → bg_gray_Image_right → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: get_back.bgGray.primary.main_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  main_image: prismic.ImageField<never>;

  /**
   * Title field in *GetBack → bg_gray_Image_right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: get_back.bgGray.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * colorText field in *GetBack → bg_gray_Image_right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: get_back.bgGray.primary.colortext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  colortext: prismic.RichTextField;

  /**
   * get Back Text field in *GetBack → bg_gray_Image_right → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: get_back.bgGray.primary.get_back_text[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  get_back_text: prismic.GroupField<
    Simplify<GetBackSliceBgGrayPrimaryGetBackTextItem>
  >;

  /**
   * underLine field in *GetBack → bg_gray_Image_right → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: get_back.bgGray.primary.underline
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  underline: prismic.ImageField<never>;
}

/**
 * bg_gray_Image_right variation for GetBack Slice
 *
 * - **API ID**: `bgGray`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GetBackSliceBgGray = prismic.SharedSliceVariation<
  "bgGray",
  Simplify<GetBackSliceBgGrayPrimary>,
  never
>;

/**
 * Primary content in *GetBack → bg_gray_image_left → Primary*
 */
export interface GetBackSliceBgGrayImageLeftPrimary {
  /**
   * Main Image field in *GetBack → bg_gray_image_left → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: get_back.bgGrayImageLeft.primary.main_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  main_image: prismic.ImageField<never>;

  /**
   * Title field in *GetBack → bg_gray_image_left → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: get_back.bgGrayImageLeft.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * colorText field in *GetBack → bg_gray_image_left → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: get_back.bgGrayImageLeft.primary.colortext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  colortext: prismic.RichTextField;

  /**
   * get Back Text field in *GetBack → bg_gray_image_left → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: get_back.bgGrayImageLeft.primary.get_back_text[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  get_back_text: prismic.GroupField<
    Simplify<GetBackSliceBgGrayImageLeftPrimaryGetBackTextItem>
  >;

  /**
   * underLine field in *GetBack → bg_gray_image_left → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: get_back.bgGrayImageLeft.primary.underline
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  underline: prismic.ImageField<never>;
}

/**
 * bg_gray_image_left variation for GetBack Slice
 *
 * - **API ID**: `bgGrayImageLeft`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GetBackSliceBgGrayImageLeft = prismic.SharedSliceVariation<
  "bgGrayImageLeft",
  Simplify<GetBackSliceBgGrayImageLeftPrimary>,
  never
>;

/**
 * Slice variation for *GetBack*
 */
type GetBackSliceVariation =
  | GetBackSliceDefault
  | GetBackSliceLeftToRight
  | GetBackSliceBgGray
  | GetBackSliceBgGrayImageLeft;

/**
 * GetBack Shared Slice
 *
 * - **API ID**: `get_back`
 * - **Description**: GetBack
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GetBackSlice = prismic.SharedSlice<
  "get_back",
  GetBackSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Cover field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.cover
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cover: prismic.ImageField<never>;

  /**
   * Hero Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  hero_title: prismic.RichTextField;

  /**
   * Hero color field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_color
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  hero_color: prismic.RichTextField;

  /**
   * Rest Hero Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.rest_hero_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  rest_hero_title: prismic.RichTextField;

  /**
   * first text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.first_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  first_text: prismic.RichTextField;

  /**
   * secound text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.secound_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  secound_text: prismic.RichTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *Personalized → Default → Primary → list container*
 */
export interface PersonalizedSliceDefaultPrimaryListContainerItem {
  /**
   * title field in *Personalized → Default → Primary → list container*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: personalized.default.primary.list_container[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Item in *Personalized → Default → Primary → list container two*
 */
export interface PersonalizedSliceDefaultPrimaryListContainerTwoItem {
  /**
   * title field in *Personalized → Default → Primary → list container two*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: personalized.default.primary.list_container_two[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Item in *Personalized → Default → Primary → list container three*
 */
export interface PersonalizedSliceDefaultPrimaryListContainerThreeItem {
  /**
   * title field in *Personalized → Default → Primary → list container three*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: personalized.default.primary.list_container_three[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Item in *Personalized → Default → Primary → list items one*
 */
export interface PersonalizedSliceDefaultPrimaryListItemsOneItem {
  /**
   * text field in *Personalized → Default → Primary → list items one*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: personalized.default.primary.list_items_one[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * image field in *Personalized → Default → Primary → list items one*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: personalized.default.primary.list_items_one[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *Personalized → Default → Primary → list items two*
 */
export interface PersonalizedSliceDefaultPrimaryListItemsTwoItem {
  /**
   * text field in *Personalized → Default → Primary → list items two*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: personalized.default.primary.list_items_two[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * image field in *Personalized → Default → Primary → list items two*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: personalized.default.primary.list_items_two[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *Personalized → Default → Primary → list items three*
 */
export interface PersonalizedSliceDefaultPrimaryListItemsThreeItem {
  /**
   * text field in *Personalized → Default → Primary → list items three*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: personalized.default.primary.list_items_three[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * image field in *Personalized → Default → Primary → list items three*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: personalized.default.primary.list_items_three[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *Personalized → Default → Primary*
 */
export interface PersonalizedSliceDefaultPrimary {
  /**
   * title field in *Personalized → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: personalized.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * titleColor field in *Personalized → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: personalized.default.primary.titlecolor
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titlecolor: prismic.RichTextField;

  /**
   * description field in *Personalized → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: personalized.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * list container field in *Personalized → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: personalized.default.primary.list_container[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  list_container: prismic.GroupField<
    Simplify<PersonalizedSliceDefaultPrimaryListContainerItem>
  >;

  /**
   * list container two field in *Personalized → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: personalized.default.primary.list_container_two[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  list_container_two: prismic.GroupField<
    Simplify<PersonalizedSliceDefaultPrimaryListContainerTwoItem>
  >;

  /**
   * list container three field in *Personalized → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: personalized.default.primary.list_container_three[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  list_container_three: prismic.GroupField<
    Simplify<PersonalizedSliceDefaultPrimaryListContainerThreeItem>
  >;

  /**
   * list items one field in *Personalized → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: personalized.default.primary.list_items_one[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  list_items_one: prismic.GroupField<
    Simplify<PersonalizedSliceDefaultPrimaryListItemsOneItem>
  >;

  /**
   * list items two field in *Personalized → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: personalized.default.primary.list_items_two[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  list_items_two: prismic.GroupField<
    Simplify<PersonalizedSliceDefaultPrimaryListItemsTwoItem>
  >;

  /**
   * list items three field in *Personalized → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: personalized.default.primary.list_items_three[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  list_items_three: prismic.GroupField<
    Simplify<PersonalizedSliceDefaultPrimaryListItemsThreeItem>
  >;
}

/**
 * Default variation for Personalized Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PersonalizedSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PersonalizedSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Personalized*
 */
type PersonalizedSliceVariation = PersonalizedSliceDefault;

/**
 * Personalized Shared Slice
 *
 * - **API ID**: `personalized`
 * - **Description**: Personalized
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PersonalizedSlice = prismic.SharedSlice<
  "personalized",
  PersonalizedSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavigationItem,
      AllDocumentTypes,
      DuringTherapySlice,
      DuringTherapySliceDefaultPrimary,
      DuringTherapySliceVariation,
      DuringTherapySliceDefault,
      GetBackSlice,
      GetBackSliceDefaultPrimaryGetBackTextItem,
      GetBackSliceDefaultPrimary,
      GetBackSliceLeftToRightPrimaryGetBackTextItem,
      GetBackSliceLeftToRightPrimary,
      GetBackSliceBgGrayPrimaryGetBackTextItem,
      GetBackSliceBgGrayPrimary,
      GetBackSliceBgGrayImageLeftPrimaryGetBackTextItem,
      GetBackSliceBgGrayImageLeftPrimary,
      GetBackSliceVariation,
      GetBackSliceDefault,
      GetBackSliceLeftToRight,
      GetBackSliceBgGray,
      GetBackSliceBgGrayImageLeft,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      PersonalizedSlice,
      PersonalizedSliceDefaultPrimaryListContainerItem,
      PersonalizedSliceDefaultPrimaryListContainerTwoItem,
      PersonalizedSliceDefaultPrimaryListContainerThreeItem,
      PersonalizedSliceDefaultPrimaryListItemsOneItem,
      PersonalizedSliceDefaultPrimaryListItemsTwoItem,
      PersonalizedSliceDefaultPrimaryListItemsThreeItem,
      PersonalizedSliceDefaultPrimary,
      PersonalizedSliceVariation,
      PersonalizedSliceDefault,
    };
  }
}
