// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  during_therapy: dynamic(() => import("./DuringTherapy")),
  get_back: dynamic(() => import("./GetBack")),
  hero: dynamic(() => import("./Hero")),
  map: dynamic(() => import("./Map")),
  personalized: dynamic(() => import("./Personalized")),
};
